=== Istorija i motivacija

LSP je kreiran od strane Microsoft-a kako bi se definisao zajednički jezik kojim jezički alati komuniciraju.
Nastao je 2016. godine, a pored Microsofta su se udružile i druge kompanije, kao što su Red Hat, Codenvy i Sourcegraph,
kako bi podržali njegov rast.

Inicijalno, Microsoft je razvio OmniSharp projekat sa ciljem da pruži "pametne" funkcionalnosti za programski jezik C#
u tekst editorima.
OmniSharp je inicijalno koristio HTTP protokol za razmenu JSON poruka.
Ubrzo je integrisan u nekoliko tekst editora, a jedan od njih bio je VS Code,
koji je takođe razvijen od strane Microsoft-a.

U istom vremenskom periodu, Microsoft je počeo sa razvojem još jednog jezičkog servera.
Ovaj jezički server je imao za cilj da podrži programski jezik TypeScript.
Koristio je standardni ulaz/izlaz kao transportni protokol,
a poruke su bile u JSON formatu po uzoru na V8 debugger protokol.

Kada je tim zadužen za razvoj VS Code editora integrisao i TypeScript jezički server,
uvideli su da je konzumacija jezičkih servera suvišno komplikovana.
Kako bi pojednostavili integraciju, počeli su da razmišljaju o opštem zajedničkom protokolu <<lsp-history>>.
Zajednički protokol omogućio bi da se integracioni kod napiše samo jednom,
i da se koristi za sve jezičke servere koji pričaju zajednički jezik.

Zajednički protokol je kao osnovu koristio protokol TypeScript jezičkog servera,
koji je uopšten i napravljen da bude jezički neutralan.
U početku, protokol je podržavao poruke dijagnostike, a kasnije je obogaćen ostalim
"pametnim" funkcionalnostima koje jedan server može da pruži.

Danas je LSP podržan od strane velikog broja tekst editora i jezičkih zajednica.
LSP je otvoren protokol i kompletna specifikacija je slobodno dostupna na
link:https://github.com/Microsoft/language-server-protocol[GitHub-u].

Razvojem standardizovanog protokola, postalo je dovoljno da jezička zajednica napravi
jedan jezički server koji pruža sve "pametne" funkcionalnosti za dati programski jezik.
Svi editori koji razumeju jezički protokol tada automatski dobijaju podršku za taj programski jezik.

LSP nije ograničen samo na programske jezike, već se može koristiti i za bilo kakve tekst-bazirane jezike ili domen-specifične jezike.

=== Tehnički detalji

Tekst editor se ponaša kao klijent koji komunicira sa jezičkim serverom.
Komunikacija se odvija slanjem poruka.

U osnovi, poruka se sastoji iz *zaglavlja* (_header_) i *sadržaja* (_content_), slično kao i HTTP protokol.
Zaglavlje i sadržaj su razdvojeni `\r\n` karakterima.

Specifikacijom nije određen transportni protokol za razmenu poruka.
U praksi klijent i server najčešće komuniciraju preko standardnog ulaza/izlaza,
ali moguća je i komunikacija preko mrežnih soketa ili bilo kojeg drugog vida međuprocesne komunikacije.

Klijent je zadužen da vodi računa o životnom veku servera.
Na klijentu je da odluči kada će startovati server i kada će ga zaustaviti.

==== Zaglavlje poruke

Zaglavlje se sastoji iz polja.
Svako polje je par ključ-vrednost, razdvojeni sa `:{nbsp}` (dvotačka praćena razmakom).
Svako polje se završava karakterima `\r\n`.

.Podržana polja u zaglavlju:
|===
| Ključ | Vrednost | Opis polja
| `Content-Length` | celobrojna vrednost | Dužina sadržaja poruke u bajtovima. *Obavezno polje*.
| `Content-Type` | string | Mime tip sadržaja. Podrazumevana vrednost je `application/vscode-jsonrpc; charset=utf-8`.
|===

==== Sadržaj poruke

Sadržaj poruke koji se razmenjuje između klijenta i servera je baziran na JSON-RPC protokolu.
JSON-RPC je protokol koji omogućava udaljen poziv procedura (_remote procedure call_) razmenom poruka u JSON formatu.

U zvaničnoj LSP specifikaciji, JSON poruke koje se razmenjuju su opisane kroz TypeScript objekte.
Isti način opisivanja poruka će biti korišćen i u ovom radu.

U vreme pisanja ovog rada, poslednja dostupna verzija LSP specifikacije je 3.x.
Po poslednjoj verziji jedini dozvoljen format kodiranja poruka je `utf-8`.

.Sve poruke sadrže minimalno JSON objekat sa `jsonrpc` poljem:
[source,typescript]
----
interface Message {
	jsonrpc: string; <1>
}
----
<1> LSP uvek koristi vrednost `"2.0"` kao verziju.

.Sve poruke se dele na 3 varijante:
. *Zahtev* (_request_)—upućen zahtev između klijenta i servera. Svaki zahtev mora imati odgovor.
. *Odgovor* (_response_)—odgovor na upućen zahtev.
. *Obaveštenje* (_notification_)—slično zahtevu, ali ne zahteva odgovor.

===== Zahtev

.Zahtev proširuje osnovnu poruku dodatnim poljima:
[source,typescript]
----
interface RequestMessage extends Message {
	id: number | string; //<1>
	method: string; //<2>
	params?: Array<any> | object; //<3>
}
----
<1> Identifikator zahteva.
<2> Naziv metode koju treba pozvati.
<3> Parametri metode.

===== Odgovor

.Odgovor proširuje osnovnu poruku dodatnim poljima:
[source,typescript]
----
interface ResponseMessage extends Message {
	id: number | string | null; //<1>
	result?: string | number | boolean | object | null; //<2>
	error?: ResponseError<any>; //<3>
}
----
<1> Identifikator zahteva.
<2> Rezultat zahteva.
<3> Rezultat u slučaju greške.

Mora postojati ili rezultat ili greška, ali ne i jedno i drugo u isto vreme.

===== Obaveštenje

.Obaveštenje proširuje osnovnu poruku dodatnim poljima:
[source,typescript]
----
interface NotificationMessage extends Message {
	method: string; //<1>
	params?: Array<any> | object; //<2>
}
----
<1> Naziv metode koju treba pozvati.
<2> Parametri metode.

Kao što se može videti, obaveštenje se razlikuje od zahteva samo u tome što obaveštenje nema `"id"` polje.
Identifikator nije potreban, zato što obaveštenje ne očekuje odgovor.

==== Redosled poruka

Odgovore obično treba slati u istom redosledu u kojem su zahtevi pristizali na server.
Server se može odlučiti na paralelno izvršavanje, pa u tom slučaju može slati odgovore u različitom redosledu.
Serveru je to dozvoljeno, ali samo ako promena redosleda ne utiče na korektnost odgovora.

Na primer, server verovatno ne može da promeni redosled zahteva za preimenovanjem promenljive i skoka na definiciju,
zato što izvršavanje jednog zahteva može uticati na rezultat drugog.

==== Osnovne JSON strukture

U nastavku su definisane neke od osnovnih JSON struktura koje se koriste u sklopu drugih poruka.

.URI:
[source,typescript]
----
type DocumentUri = string; //<1>
----
<1> Preko mreže se URI prenosi kao običan string, ali je zbog jasnoće u specifikaciji prikazan kao poseban tip.

.Pozicija (_position_):
[source,typescript]
----
interface Position {
	line: number; //<1>
	character: number; //<2>
}
----
<1> Redni broj linije (indeksiranje kreće od nule).
<2> Pomeraj (_offset_) karaktera u liniji.
Vrednost `character` predstavlja prostor između `character` i `character + 1`.

.Raspon (_range_):
[source,typescript]
----
interface Range { //<1>
	start: Position;
	end: Position;
}
----
<1> Raspon se može posmatrati kao selekcija u editoru.

.Lokacija (_location_):
[source,typescript]
----
interface Location { //<1>
	uri: DocumentUri;
	range: Range;
}
----
<1> Predstavlja lokaciju unutar resursa. Na primer određena linija u datoteci.

.Identifikator dokumenta (_text document identifier_):
[source,typescript]
----
interface TextDocumentIdentifier {
	uri: DocumentUri; //<1>
}
----
<1> Dokumenti se identifikuju na osnovu URI-ja.

.Dokument (_text document item_):
[source,typescript]
----
interface TextDocumentItem { //<1>
	uri: DocumentUri;
	languageId: string;
	version: number;
	text: string;
}
----
<1> Predstavlja jednu stavku prenosa dokumenta od klijenta do servera.

.Pozicija u dokumentu (_text document position_)
[source,typescript]
----
interface TextDocumentPositionParams { //<1>
	textDocument: TextDocumentIdentifier;
	position: Position;
}
----
<1> Predstavlja jednu poziciju u jednom konkretnom dokumentu.

==== Poruke za upravljanje životnim ciklusom servera

===== Zahtev za inicijalizaciju (*_initialize request_*)

Zahtev za inicijalizaciju se šalje kao prvi zahtev serveru od strane klijenta.

.Ukoliko dobije neki drugi zahtev ili obaveštenje pre zahteva za inicijalizaciju, server treba da uradi sledeće:
* U slučaju zahteva, treba u odgovoru da pošalje kod greške `-32002`.
* U slučaju obaveštenja, treba da ignoriše obaveštenje.

Jedini izuzetak za prethodno navedeno je obaveštenje o zaustavljanju, u tom slučaju server treba da odreaguje.
Na ovaj način moguće je zaustaviti server bez prethodnog zahteva za inicijalizacijom.

Dok server ne pošalje odgovor na zahtev za inicijalizaciju, klijent ne sme slati dodatne zahteve ili obaveštenja.
Takođe, ni server ne sme slati klijentu bilo kakve zahteve ili obaveštenja dok ne pošalje odgovor o uspešnoj inicijalizaciji.

Zahtev za inicijalizaciju se sme poslati samo jednom.

.Zahtev za inicijalizaciju:
[source,typescript]
----
// method: 'initialize'
// params: InitializeParams

interface InitializeParams {
	processId: number | null; //<1>
	rootUri: DocumentUri | null; //<2>
	capabilities: ClientCapabilities; //<3>
	// ... izostavljena manje bitna polja
}
----
<1> Identifikator roditeljskog procesa koji je startovao server.
<2> URI korenskog direktorijuma radnog okruženja.
U slučaju da nijedan direktorijum nije otvoren ima vrednost `null`.
<3> LSP funkcionalnosti koje klijent podržava.

.Odgovor na zahtev za inicijalizaciju:
[source,typescript]
----
// result: InitializeResult

interface InitializeResult {
	capabilities: ServerCapabilities; //<1>
}

interface ServerCapabilities { //<2>
	textDocumentSync?: TextDocumentSyncOptions | number;
	hoverProvider?: boolean;
	completionProvider?: CompletionOptions;
	definitionProvider?: boolean;
	// ...
}
----
<1> LSP funkcionalnosti koje server podržava.
<2> Prikazane neke od mogućih funkcionalnosti.

===== Zahtev za zaustavljanje (*_shutdown request_*)

Zahtev za zaustavljanje se šalje serveru od strane klijenta.

.Zahtev za zaustavljanje:
[source,typescript]
----
// method: 'shutdown'
// params: void
----

.Odgovor na zahtev za zaustavljanje:
[source,typescript]
----
// result: null
----

Server treba da oslobodi resurse i pripremi se za zaustavljanje,
ali ne treba da ugasi proces (u suprotnom, klijent možda ne bi uspeo da pročita odgovor).
Kada klijent dobije odgovor, treba da pošalje obaveštenje o izlasku, nakon čega server treba potpuno da se zaustavi.

===== Obaveštenje o izlasku

.Obaveštenje o izlasku:
[source,typescript]
----
// method: 'exit'
// params: void
----

Izlazni kod servera treba da bude `0` u slučaju da je prethodno dobio zahtev za zaustavljanje,
a u suprotnom izlazni kod treba da bude `1`.

==== Poruke za sinhronizaciju teksta

Tekst editor obaveštava jezički server o događajima, odnosno interakcijama koje korisnik vrši nad dokumentima.

.Neki od mogućih događaja su:
`didOpen`:: Korisnik otvorio datoteku.
`didChange`:: Korisnik napravio izmene u datoteci.
`didSave`:: Korisnik je sačuvao datoteku.
`didClose`:: Korisnik je zatvorio datoteku.

Jezički server treba da "sluša" događaje i interno vodi evidenciju o svim otvorenim datotekama i njihovim sadržajem.
Kada se dogodi određeni događaj, klijent u poruci ne šalje samo URI dokumenta već njegov kompletan sadržaj u vidu stringa.
Ovo je neophodno kako bi sve funkcionalnosti radile bez potrebe da korisnik prethodno sačuva datoteku na medijum za trajno čuvanje podataka.

Na primer, korisnik je napravio izmene u datoteci i između ostalog dodao novi identifikator.
Korisnik pozicionira kursor na pojavu novonastalog identifikatora i zatraži da se izvrši skok na njegovu definiciju.
Ako bi server u `didChange` događaju dobio samo URI dokumenta koji je promenjen,
morao bi da pročita sadržaj tog dokumenta sa diska.
Međutim, pošto korisnik još uvek nije sačuvao svoje izmene, server ih neće videti.
Prema tome, server neće pronaći definiciju novonastalog identifikatora.
Sa druge strane, ako u svakom `didChange` događaju klijent prosledi i sadržaj trenutnog stanja datoteke,
server može interno čuvati sadržaj svih otvorenih datoteka u baferima.
Na taj način, server uvek u memoriji ima trenutno stanje koje i korisnik vidi.

S obzirom da korisnik može otvoriti veoma veliku datoteku, prosleđivanje kompletnog sadržaja serveru prilikom svake sitne izmene
može biti veoma zahtevno i može usporiti rad.
Zbog optimizacije, klijent može poslati samo deo teksta koji je izmenjen i poziciju na kojoj je napravljena izmena.
Na taj način dobijamo kraće poruke koje se razmenjuju, ali server ima dodatni posao da modifikuje svoje interne bafere.

Prethodno navedenu funkcionalnost ne moraju podržavati svi jezički serveri.
Prilikom slanja odgovora na zahtev za inicijalizaciju,
server može specificirati na koji način želi da mu se dostavljaju izmene.
U polju `textDocumentSync` treba navesti odgovarajuću konstantu.

.Primer izbora željenog načina sinhronizacije:
[source,json]
----
{
	"jsonrpc": "2.0",
	"id": 123, <1>
	"result": {
		"capabilities": {
			"textDocumentSync": ..., <2>
			...
		}
		...
	}
}
----
<1> Odgovor na zahtev za inicijalizaciju.
<2> Polje može imati sledeće vrednosti: +
`0`:: Dokumenti se neće sinhronizovati uopšte.
`1`:: Dokumenti se sinhronizuju tako što se uvek šalje kompletan sadržaj dokumenta.
`2`:: Dokumenti se sinhronizuju inkrementalnim ažuriranjem.

.Obaveštenje o `didOpen` događaju:
[source,typescript]
----
// method: 'textDocument/didOpen'
// params: DidOpenTextDocumentParams

interface DidOpenTextDocumentParams {
	textDocument: TextDocumentItem;
}
----

.Obaveštenje o `didClose` događaju:
[source,typescript]
----
// method: 'textDocument/didClose'
// params: DidCloseTextDocumentParams

interface DidCloseTextDocumentParams {
	textDocument: TextDocumentIdentifier;
}
----

.Obaveštenje o `didChange` događaju:
[source,typescript]
----
// method: 'textDocument/didChange'
// params: DidChangeTextDocumentParams

interface DidChangeTextDocumentParams {
	textDocument: VersionedTextDocumentIdentifier;
	contentChanges: TextDocumentContentChangeEvent[]; //<1>
}

interface TextDocumentContentChangeEvent {
	range?: Range;
	rangeLength?: number;
	text: string;
}
----
<1> Lista pojedinačnih izmena.
U slučaju da je izabran način sinhronizacije sa kompletnim prenosom sadržaja,
tada će postojati samo jedan element niza i polja `range` i `rangeLength` će biti izostavljena.

==== Poruke za objavljivanje dijagnostike

Poruke dijagnostike imaju za cilj da korisniku prikažu greške, upozorenja ili informacije u toku samog unosa teksta.

Poruke dijagnostike ne traži klijent od servera, već ih server sam isporučuje kada je to neophodno.
Iz tog razloga ovakve poruke su implementirane kao obaveštenja, a ne kao par zahtev–odgovor.

Kada određena dijagnostika više nije aktuelna, server je dužan da pošalje osveženu listu klijentu.
Ukoliko je lista dijagnostika prazna, server je dužan da pošalje praznu listu klijentu.
Stara lista dijagnostika se uvek zamenjuje novom listom, klijent ne vrši spajanje lista ni na koji način.

.Obaveštenje o dijagnostici:
[source,typescript]
----
// method: 'textDocument/publishDiagnostics'
// params: PublishDiagnosticsParams

interface PublishDiagnosticsParams {
	uri: DocumentUri; //<1>
	diagnostics: Diagnostic[]; //<2>
}
----
<1> URI dokumenta na koji se dijagnostika odnosi.
<2> Lista dijagnostika.

.Objekat koji opisuje pojedinačnu poruku dijagnostike:
[source,typescript]
----
interface Diagnostic {
	range: Range; //<1>
	severity?: number; //<2>
	message: string; //<3>
	// ...
}
----
<1> Raspon u dokumentu za koji se dijagnostika odnosi.
<2> Ozbiljnost greške. Može imati vrednost od `1` do `4`, u zavisnosti od toga da li je u pitanju
greška (`error`), upozorenje (`warning`), informacija (`information`), ili nagoveštaj (`hint`) respektivno.
<3> Poruka koja se prikazuje korisniku.

==== Poruke za ostale jezičke funkcionalnosti

LSP podržava preko 20 dodatnih jezičkih funkcionalnosti.
Sa obzirom da ovaj rad ne predstavlja kompletnu specifikaciju protokola jezičkih servera,
u nastavku će pored prethodno opisanih poruka o dijagnostici biti opisane još 3 dodatne funkcionalnosti.

U implementaciji jezičkog servera za programski jezik miniC, koja će biti opisana u nastavku rada,
takođe će biti implementirane ove 4 funkcionalnosti.

===== Dovršavanje reči (*_word completion_*)

Automatsko dovršavanje reči može pomoći ako u kodu postoje dugački identifikatori.
Dovoljno je da korisnik ukuca nekoliko početnih slova, a zatim će mu tekst editor prikazati
padajući meni sa mogućim opcijama iz kojeg može odabrati željenu stavku.

Dovršavanje reči takođe može biti korisno ako korisnik nije siguran koje su funkcionalnosti dostupne
u API-ju određene biblioteke.
Dovoljno je da ukuca nekoliko početnih slova, a onda može u padajućem meniju da pronađe da li postoji
željena stavka.

Tekst editor, odnosno klijent je zadužen da pošalje zahtev za dovršavanjem reči kada je to potrebno.

.Zahtev za dovršavanjem reči:
[source,typescript]
----
// method: 'textDocument/completion'
// params: CompletionParams

interface CompletionParams extends TextDocumentPositionParams { //<1>
	context?: CompletionContext; //<2>
}
----
<1> Parametar nasleđuje `TextDocumentPositionParams`, pa tako opisuje poziciju u tekst dokumentu na kojoj se korisnik trenutno nalazi.
<2> `CompletionParams` se opciono proširuje poljem `context` koje predstavlja dodatno objašnjenje pod kojim uslovima se dogodio zahtev.

.Odgovor na zahtev za dovršavanjem reči:
[source,typescript]
----
// result: CompletionItem[] | null

interface CompletionItem {
	label: string; //<1>
	detail?: string; //<2>
	// ...
}
----
<1> Sadržaj koji će dopuniti ako se izabere ta stavka iz liste.
<2> Dodatne informacije koje će biti prikazane korisniku.

===== "Lebdeće" (*_hover_*) poruke

Klijent može zatražiti od servera dodatne informacije o identifikatoru koje se prikazuju u vidu "lebdeće" poruke korisniku.

.Zahtev:
[source,typescript]
----
// method: 'textDocument/hover'
// params: TextDocumentPositionParams
----

.Odgovor:
[source,typescript]
----
// result: Hover | null

interface Hover {
	contents: MarkedString | MarkedString[] | MarkupContent; //<1>
	range?: Range; //<2>
}
----
<1> Informacije koje se prikazuju korisniku, napisane u Markdown formatu.
<2> Opciono može sadržati i raspon u tekst dokumentu kako bi editor vizuelno drugačije prikazao identifikator.

===== Skok na definiciju (*_go to definition_*)

Skok na definiciju se može koristiti kao jedan od načina za navigaciju kroz kod.

.Zahtev:
[source,typescript]
----
// method: 'textDocument/definition'
// params: TextDocumentPositionParams
----

.Odgovor:
[source,typescript]
----
// result: Location | Location[] | null
----
